# Client-Side Container - Frontend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-client
spec:
  selector:
    matchLabels:
      app: my-client
  replicas: 1
  template:
    metadata:
      labels:
        app: my-client
    spec:
      containers:
        - name: application-frontend
          image: afzal442/supportdesk-app-frontend:v1
          # imagePullPolicy: Never
          ports:
          - containerPort: 80
---
# Client Service
apiVersion: v1
kind: Service
metadata:
  name: client-service
  labels:
    app: my-client
spec:
  type: LoadBalancer
  selector:
    app: my-client
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  sessionAffinity: None
---