# Server-Side Container - Backend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-server
spec:
  selector:
    matchLabels:
      app: my-server
  replicas: 1
  template:
    metadata:
      labels:
        app: my-server
    spec:
      containers:
        - name: application-backend
          image: afzal442/supprtdsk-app-backend:v1
          ports:
            - containerPort: 5000
---
# Client Service
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: my-server
spec:
  type: ClusterIP
  selector:
    app: my-server
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 80
  sessionAffinity: None
---